# Site settings
title: Arne Küderle
email: a.kuederle@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A small blog/notebook, where I write about computer related stuff I learn.
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  AKuederle

# Build settings
markdown: kramdown
kramdown:
  input: GFM

gems:
- jekyll-sitemap

pygments: true
